name: Build LaTeX Document
on:
  push:
    branches: ["main"]
    paths:
      - "**.tex"
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-latex-extra

      - name: Compile LaTeX files
        run: |
          cd latex_codes
          for file in *.tex; do
            pdflatex "$file"
          done
          mv *.pdf ../resume_PDFs/

      - name: Check in PDFs
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add resume_PDFs/
          git commit -m "Update compiled PDFs [skip ci]" || echo "No changes to commit"
          git push
